config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "same/new", to: "same#new" 
  post "same", to: "same#create"
  post 'subscribe', to: "home#subscribe", as:'subscribe'
end

app/models/following.rb
class Following < ActiveRecord::Base
	belongs_to :user_a, class_name: :User, foreign_key: :a_id
	belongs_to :user_b, class_name: :User, foreign_key: :b_id
        validates_uniqueness_of :user_a, :scope => [:user_b]
end

app/models/same.rb
class Same < ActiveRecord::Base
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment :image, :presence => true,
  		:content_type => { :content_type => "image/jpeg" },
  		:size => { :in => 0..10000.kilobytes }
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sames
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  	def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if current_user == nil 
			redirect_to new_user_session_path
		else
			@current_user_name = current_user.username
			puts @current_user_name
			subs = Following.where(b_id: current_user.id)
			sub_ids = Array.new
			sub_ids.push(current_user.id)
			@sames = Array.new
			subs.each do |s|
				sub_ids.push(s.a_id)
			end
			Same.find_each do |a|
				if sub_ids.include? a.user_id
					@sames.push(a)
				end
			end
			puts "****************"
			puts @sames
		end
	end

	def subscribe
		puts "Hello"
		@new_f = Following.new
		@user_b = User.find_by username: params[:sub]
		if @user_b == nil
			flash[:error] = "Invalid Username"
			redirect_to :root
		else
			@new_f.a_id = current_user.id
			@new_f.b_id = @user_b.id
			if @new_f.save
				puts "Success"
			else
				puts "Failure"
			end
			redirect_to :root
		end
		
	end
end

app/controllers/same_controller.rb
class SameController < ApplicationController
	def index
		@same = Same.all
	end

	def new
		@same = Same.new
	end

	def create
		@same = Same.create same_params
		@same.user_id = current_user.id
		puts current_user.id
		if @same.save
			redirect_to :root
		else
			puts @same.errors.full_messages.to_sentence
			redirect_to same_new_path
		end
	end

	private 
	def same_params
		params.require(:same).permit(:image)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/same_helper.rb
module SameHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang = en>
<head>
	<title>Spam</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="assets/index.css">
  	<link rel="icon" href="images/samelogo.png" type="image/png" sizes="16x16">
</head>
<body>
	<div id="title_section">
		<h1 id="title_header" style="margin-top: 0px;">actually spam.</h1>
	</div>
	<div id="subs">
	<h2>Subscribe to a user</h2>
	<%= form_tag subscribe_path do %>
	  <%= label_tag :sub, "Who do you want to subscribe to?" %>
	  <%= text_area_tag :sub %>
	  <%= submit_tag "Subscribe!" %>
	<% end %>
	<%= button_to "Add a Spam", same_new_path, :class => "button medium", :method => :get %>
	<%= button_to "Log Out", destroy_user_session_path, :class => "button medium", :method => :delete %>
	</div> 
	<div id="pics">
		<div id="header">
			 <h3> Welcome <%= @current_user_name %></h3> 
		</div>
		<% @sames.reverse.each do |s| %>
			<div class= "usernames">
				<%= User.find(s.user_id).username %>
			</div>
			<br>
			<div class= "image">
				<%=image_tag s.image.url %>
			</div>
			<br><br>
		<% end %>
	</div>
	<br>
	<br>
	<br>
</body>

<script>
		function changeImage(a) {
			if (a==""){
        		$('#photo_section').fadeTo("medium", 1);
        	}
        	else{
        		$('#photo_section').fadeTo("medium", .2);
        		$('#title_header').fadeTo("medium", .5);
        	}
        	
        	setTimeout(function() {document.getElementById("main_image").src=a;},350);
        	
    	}
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>actuallyspam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/same/new.html.erb
<%= simple_form_for @same, url: same_path do |form| %>
  <%= form.input :image, as: :file %>
  <%= form.submit :submit %> 
<% end %>